version: '3'
services:
  #php-fpm setup
  bayad-connect:
    build: .
    container_name: bayad-connect
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      #- ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment: 
      CI_ENV: 'development'
      CI_DB_HOSTNAME: 'bayad-connect-pilot-db:3306'
      CI_DB_USERNAME: 'root'
      CI_DB_PASSWORD: 'bayadconnect'
      CI_DB_DATABASE: 'bayad-connect-pilot'
      #CI_BASE_URL: 'https://bayadcenterservices.cis.com.ph/sss-prn-generation'
      CI_BASE_URL: 'http://localhost:3020/'
    networks:
      - bayad-connect
  
  #nginx
  bayad-connect-nginx:
    image: nginx:alpine
    container_name: byaad-connect-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "3020:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/errors:/etc/nginx/errors
    networks:
      - bayad-connect
  #mysql
  bayad-connect-db:
    image: mysql:5.6
    container_name: bayad-connect-pilot-db
    restart: unless-stopped
    tty: true
    ports:
      - "3100:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: bayad-connect-pilot
      MYSQL_ROOT_HOST: "%"
      #MYSQL_PASSWORD: bayadconnect
      MYSQL_ROOT_PASSWORD: bayadconnect
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - bayad-connect
networks:
  bayad-connect:
    driver: bridge
volumes:
  dbdata:
    driver: local